# Generated by Django 4.2.2 on 2023-07-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barfoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_refid', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELED', 'Canceled'), ('PENDING', 'Pending')], max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='barfoo.flight')),
            ],
        ),
    ]
