# Generated by Django 4.2.2 on 2023-07-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barfoo', '0002_flightbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightbook',
            old_name='booking_refid',
            new_name='booking_ref',
        ),
    ]
