# Generated by Django 4.2.2 on 2023-07-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barfoo', '0004_flightbook_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='flight',
        ),
    ]
