# Generated by Django 4.2.2 on 2023-07-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barfoo', '0005_remove_passenger_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbook',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('PENDING', 'Pending')], max_length=10),
        ),
    ]
